name: pgee
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dynamic_color: ^1.4.0
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^3.1.17
  flutter_slidable: ^1.3.0
  url_launcher: ^6.1.4
  localstorage: ^4.0.0+1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - .env
