name: Flutter Build APK

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

env:
  ANDROID_API: ${{ secrets.ANDROID_API }}
  IOS_API: ${{ secrets.IOS_API }}

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_ANDROID_API: ${{ secrets.ANDROID_API }}
          ENV_IOS_API: ${{ secrets.IOS_API }}

      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.${{github.run_number}}
          token: ${{ secrets.TOKEN }}
