name: Flutter Build APK

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

env:
  ANDROID_API: ${{ secrets.ANDROID_API }}
  IOS_API: ${{ secrets.IOS_API }}

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: "Create env file"
        run: |
          touch .env
          echo API_ENDPOINT=${{ secrets.ANDROID_API }} >> .env
          echo API_KEY=${{ secrets.IOS_API }} >> .env
          cat .env

      - name: "Show files"
        run: |
          ls -la

  build_android:
    name: Build APK
    runs-on: ubuntu-latest
    needs: [create]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Pub Get Packages
        run: flutter pub get

      - name: "Show files"
        run: |
          ls -la

      - name: Build APK
        run: flutter build apk --release

      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.${{github.run_number}}
          token: ${{ secrets.TOKEN }}
